//
// Created by Alys Abet on 8/25/21.
//

#ifndef CPP_MODULE_PRESIDENTIALPARDONFORM_HPP
#define CPP_MODULE_PRESIDENTIALPARDONFORM_HPP


class PresidentialPardonForm {

};


#endif //CPP_MODULE_PRESIDENTIALPARDONFORM_HPP
